apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: arunm1-poi-backend-app-dev
  annotations:
    argocd/app-name: arunm1-poi-backend-app-dev
    backstage.io/kubernetes-id: arunm1-poi-backend-app
    backstage.io/kubernetes-namespace: arunm1
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-atl/arunm1-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/dev-pipelines/ns/arunm1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.j0i9yf30.eastus2.aroapp.io/k8s/ns/arunm1/deployments/arunm1-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.j0i9yf30.eastus2.aroapp.io/#https://github.com/rhdh-atl/arunm1-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/arunmamgai"
  system: workshop-system-arunm1
  providesApis:
    - backend-api-arunm1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-arunm1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/arunmamgai"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-arunm1
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://arunm1-poi-backend-app-arunm1.apps.j0i9yf30.eastus2.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-atl/arunm1-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/arunmamgai"
  system: workshop-system-arunm1
  definition:
    $text: https://github.com/rhdh-atl/arunm1-backend/tree/main/src/main/resources/META-INF/openapi.yaml
